### ISSUE TITLE
Uploading images returns me to the main screen

### ISSUE THREAD

**Issue by sgoggins** [TheForgottenTime/RJI-group14#15]
**Describe the bug:**
I provide a local path to photos, but nothing happens when I hit "upload". I am just returned back to the main screen of RJI photos. 

**To Reproduce:**
1. Go to upload
2. Put a local directory path in 
3. Click upload

**Expected behavior:**
I would get some kind of feedback, and if there was an error uploading, I would know that. 

**Screenshots**
![image](https://user-images.githubusercontent.com/379847/57307078-87b3c400-70a9-11e9-8817-cf7901dffb6f.png)

**Desktop (please complete the following information):**
- OS: [e.g. macOS v10.14.1]
- Browser: [e.g. Chrome v64.5.13, Safari v12.0.1]

**Additional context**

**Comment by ghost** [comment]
Upload functionality is designed to run from http://rji.augurlabs.io to avoid having to host the images ourselves. The way the function is to be used is to post a directory containing hyperlinks that point directly to the photographs the user wishes to upload (Ex: http://rji.augurlabs.io/20170902_MuMsu/1q/).

**Comment by ghost** [comment]
A solution to this problem would be adding a text description of the intended way to use the function.

**Comment by ghost** [comment]
Description added, including a link to http://rji.augurlabs.io
